// Using window.ExcelJS and window.saveAs from CDN to bypass npm install issues
// No imports needed here.

// Theme Colors
const ORANGE_THEME = 'FFF97316'; // Tailwind orange-500
const RED = 'FFEF4444';
const GREEN = 'FF22C55E';
const YELLOW = 'FFEAB308';

const applyHeaderStyle = (worksheet, headerRowIndex = 1) => {
  const row = worksheet.getRow(headerRowIndex);
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ORANGE_THEME } };
  row.alignment = { vertical: 'middle', horizontal: 'center' };
  
  worksheet.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex, column: worksheet.columns.length }
  };
  
  worksheet.views = [{ state: 'frozen', ySplit: headerRowIndex }];
};

const autoFitColumns = (worksheet) => {
  worksheet.columns.forEach(column => {
    let maxLength = 10;
    column.eachCell({ includeEmpty: true }, cell => {
      const columnLength = cell.value ? cell.value.toString().length : 10;
      if (columnLength > maxLength) maxLength = columnLength;
    });
    column.width = maxLength + 2;
  });
};

const formatCurrency = (worksheet, columnLetters) => {
  columnLetters.forEach(col => {
    worksheet.getColumn(col).numFmt = '₹#,##0.00';
  });
};

const colorCodeStatus = (worksheet, statusColIndex, startRow = 2) => {
  const col = worksheet.getColumn(statusColIndex);
  col.eachCell({ includeEmpty: true }, (cell, rowNumber) => {
    if (rowNumber >= startRow && cell.value) {
      const s = cell.value.toString().toLowerCase();
      let color = null;
      if (s === 'paid' || s === 'approved') color = GREEN;
      else if (s.includes('pending') || s.includes('due') || s.includes('partially')) color = YELLOW;
      else if (s.includes('overdue') || s === 'rejected') color = RED;
      
      if (color) {
        cell.font = { bold: true, color: { argb: color } };
      }
    }
  });
};

const addSummaryTop = (worksheet, stats) => {
  // We'll insert rows at the top for summary
  worksheet.spliceRows(1, 0, 
    ['Total Residents', stats?.totalStudents || 0, '', 'Total PG Revenue', `₹${stats?.expectedRev || 0}`],
    ['Occupied Beds', stats?.occupiedBeds || 0, '', 'Collected Revenue', `₹${stats?.totalCollected || 0}`],
    ['Vacant Beds', stats?.vacantBeds || 0, '', 'Pending Revenue', `₹${stats?.pendingRev || 0}`],
    ['Pending Payments', stats?.pendingPayments || 0, '', 'Total Mess Subscribers', stats?.monthlyMessSubscribers || 0],
    ['Report Generated On', new Date().toLocaleString(), '', 'Generated By', 'Admin'],
    [] // Empty row before data
  );

  // Style summary
  for(let i=1; i<=5; i++) {
    const row = worksheet.getRow(i);
    row.getCell(1).font = { bold: true };
    row.getCell(4).font = { bold: true };
  }
};

const downloadWorkbook = async (workbook, filename) => {
  const buffer = await workbook.xlsx.writeBuffer();
  window.saveAs(new Blob([buffer]), filename);
};


// Helper to group flat beds array into rooms
const groupMatrixBeds = (bedsArray) => {
  if (!bedsArray || bedsArray.length === 0) return [];
  if (bedsArray[0].cots) return bedsArray;
  
  const grouped = bedsArray.reduce((acc, bed) => {
    if (!acc[bed.roomNumber]) {
      acc[bed.roomNumber] = {
        roomNumber: bed.roomNumber,
        floor: bed.floorName || 'Unknown',
        floorName: bed.floorName || 'Unknown',
        cots: []
      };
    }
    acc[bed.roomNumber].cots.push(bed);
    return acc;
  }, {});
  
  const rooms = Object.values(grouped);
  rooms.forEach(r => r.capacity = r.cots.length);
  return rooms;
};

// 1. Export PG Report
export const exportPGReport = async (dashboardData) => {
  const { matrixBeds, stats } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('PG Residents Data');

  worksheet.columns = [
    { header: 'S.No', key: 'sno' },
    { header: 'Student ID', key: 'studentId' },
    { header: 'Booking ID', key: 'bookingId' },
    { header: 'Student Name', key: 'name' },
    { header: 'Father/Guardian Name', key: 'fatherName' },
    { header: 'Mobile Number', key: 'phone' },
    { header: 'WhatsApp Number', key: 'whatsappNumber' },
    { header: 'Emergency Contact', key: 'emergencyContact' },
    { header: 'Email Address', key: 'email' },
    { header: 'Room Number', key: 'room' },
    { header: 'Cot Number', key: 'cot' },
    { header: 'Floor', key: 'floor' },
    { header: 'Sharing Type', key: 'sharing' },
    { header: 'Monthly Rent', key: 'rent' },
    { header: 'Stay Duration', key: 'duration' },
    { header: 'Expected Joining Date', key: 'joining' },
    { header: 'Booking Date', key: 'bookingDate' },
    { header: 'Booking Status', key: 'bookingStatus' },
    { header: 'Payment Status', key: 'paymentStatus' },
    { header: 'Amount Paid', key: 'paid' },
    { header: 'Amount Pending', key: 'pending' },
    { header: 'Due Date', key: 'dueDate' },
    { header: 'Remarks', key: 'remarks' },
    { header: 'Verified By', key: 'verifiedBy' },
    { header: 'Verification Date', key: 'verificationDate' }
  ];

  let sno = 1;
  let totalRent = 0, totalPaid = 0, totalPending = 0;
  
  const groupedRooms = groupMatrixBeds(matrixBeds);

  groupedRooms.forEach(room => {
    room.cots.forEach(cot => {
      if (cot.occupied && cot.studentName) {
        worksheet.addRow({
          sno: sno++,
          studentId: cot.studentId || 'N/A',
          bookingId: cot.admissionNumber || 'N/A',
          name: cot.studentName,
          fatherName: cot.fatherName || 'N/A',
          phone: cot.phone || 'N/A',
          whatsappNumber: cot.whatsappNumber || 'N/A',
          emergencyContact: cot.emergencyContact || 'N/A',
          email: cot.email || 'N/A',
          room: room.roomNumber,
          cot: cot.bedNumber,
          floor: room.floor,
          sharing: `${room.capacity} Sharing`,
          rent: cot.rentPerBed || 0,
          duration: cot.agreementEndDate ? '11 Months' : 'N/A',
          joining: cot.joiningDate || 'N/A',
          bookingDate: cot.admissionDate || 'N/A',
          bookingStatus: cot.reservationStatus || 'Occupied',
          paymentStatus: cot.paymentStatus || 'Paid',
          paid: (cot.rentPerBed || 0) - (cot.pendingAmount || 0),
          pending: cot.pendingAmount || 0,
          dueDate: cot.nextDueDate || 'N/A',
          remarks: cot.notes || '',
          verifiedBy: 'Admin',
          verificationDate: cot.lastPaymentDate || 'N/A'
        });

        totalRent += cot.rentPerBed || 0;
        totalPending += cot.pendingAmount || 0;
        totalPaid += (cot.rentPerBed || 0) - (cot.pendingAmount || 0);
      }
    });
  });

  worksheet.addRow({});
  worksheet.addRow({
    sharing: 'TOTALS',
    rent: totalRent,
    paid: totalPaid,
    pending: totalPending
  }).font = { bold: true };

  addSummaryTop(worksheet, stats);
  applyHeaderStyle(worksheet, 7);
  autoFitColumns(worksheet);
  formatCurrency(worksheet, ['N', 'T', 'U']); 
  colorCodeStatus(worksheet, 19, 8); 

  const monthYear = new Date().toLocaleString('default', { month: 'long', year: 'numeric' }).replace(' ', '_');
  await downloadWorkbook(workbook, `PG_Report_${monthYear}.xlsx`);
};

// 2. Export Mess Report
export const exportMessReport = async (dashboardData) => {
  const { messSubscribers, stats } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Monthly Mess Data');

  worksheet.columns = [
    { header: 'S.No', key: 'sno' },
    { header: 'Subscriber ID', key: 'id' },
    { header: 'Full Name', key: 'name' },
    { header: 'Mobile Number', key: 'phone' },
    { header: 'WhatsApp Number', key: 'whatsapp' },
    { header: 'Email', key: 'email' },
    { header: 'Address', key: 'address' },
    { header: 'Occupation', key: 'occupation' },
    { header: 'College / Company', key: 'college' },
    { header: 'Meal Preference', key: 'meal' },
    { header: 'Start Date', key: 'start' },
    { header: 'Subscription Duration', key: 'duration' },
    { header: 'Monthly Mess Fee', key: 'fee' },
    { header: 'Payment Status', key: 'status' },
    { header: 'Amount Paid', key: 'paid' },
    { header: 'Amount Pending', key: 'pending' },
    { header: 'Remarks', key: 'remarks' },
    { header: 'UTR Number', key: 'utr' },
    { header: 'Verified By', key: 'verifiedBy' },
    { header: 'Verification Date', key: 'verificationDate' }
  ];

  let sno = 1;
  let totalFee = 0, totalPaid = 0, totalPending = 0;

  messSubscribers.forEach(sub => {
    worksheet.addRow({
      sno: sno++,
      id: sub._id.toString().slice(-6).toUpperCase(),
      name: sub.name,
      phone: sub.phone,
      whatsapp: sub.whatsappNumber || sub.phone,
      email: sub.email || 'N/A',
      address: sub.fullAddress || 'N/A',
      occupation: sub.occupation || 'N/A',
      college: sub.collegeCompany || 'N/A',
      meal: sub.mealPreference || 'N/A',
      start: sub.expectedJoiningDate ? new Date(sub.expectedJoiningDate).toLocaleDateString() : 'N/A',
      duration: '1 Month',
      fee: 3000,
      status: sub.paymentStatus || 'Pending',
      paid: sub.paymentStatus === 'Verified' ? 3000 : 0,
      pending: sub.paymentStatus === 'Verified' ? 0 : 3000,
      remarks: 'External Mess',
      utr: sub.utrNumber || 'N/A',
      verifiedBy: sub.paymentStatus === 'Verified' ? 'Admin' : 'N/A',
      verificationDate: sub.paymentStatus === 'Verified' ? new Date().toLocaleDateString() : 'N/A'
    });
    totalFee += 3000;
    if (sub.paymentStatus === 'Verified') totalPaid += 3000;
    else totalPending += 3000;
  });

  worksheet.addRow({});
  worksheet.addRow({
    duration: 'TOTALS',
    fee: totalFee,
    paid: totalPaid,
    pending: totalPending
  }).font = { bold: true };

  addSummaryTop(worksheet, stats);
  applyHeaderStyle(worksheet, 7);
  autoFitColumns(worksheet);
  formatCurrency(worksheet, ['M', 'O', 'P']);
  colorCodeStatus(worksheet, 14, 8);

  const monthYear = new Date().toLocaleString('default', { month: 'long', year: 'numeric' }).replace(' ', '_');
  await downloadWorkbook(workbook, `Monthly_Mess_Report_${monthYear}.xlsx`);
};

// 3. Combined Report
export const exportCombinedReport = async (dashboardData) => {
  const workbook = new window.ExcelJS.Workbook();
  const { matrixBeds, messSubscribers, stats } = dashboardData;
  
  // Sheet 1: Summary
  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [{ header: 'Metric', key: 'metric' }, { header: 'Value', key: 'val' }];
  summarySheet.addRow({ metric: 'Total Residents', val: stats?.totalStudents || 0 });
  summarySheet.addRow({ metric: 'Occupied Beds', val: stats?.occupiedBeds || 0 });
  summarySheet.addRow({ metric: 'Vacant Beds', val: stats?.vacantBeds || 0 });
  summarySheet.addRow({ metric: 'Total PG Revenue', val: stats?.expectedRev || 0 });
  summarySheet.addRow({ metric: 'Collected Revenue', val: stats?.totalCollected || 0 });
  summarySheet.addRow({ metric: 'Pending Revenue', val: stats?.pendingRev || 0 });
  summarySheet.addRow({ metric: 'Total Monthly Mess Subscribers', val: stats?.monthlyMessSubscribers || 0 });
  summarySheet.addRow({ metric: 'Report Generated On', val: new Date().toLocaleString() });
  autoFitColumns(summarySheet);
  
  // Sheet 2: Residents
  const resSheet = workbook.addWorksheet('PG Residents');
  resSheet.columns = [
    { header: 'Name', key: 'name' },
    { header: 'Room', key: 'room' },
    { header: 'Cot', key: 'cot' },
    { header: 'Rent', key: 'rent' },
    { header: 'Pending', key: 'pending' }
  ];
  const groupedRooms = groupMatrixBeds(matrixBeds);
  groupedRooms.forEach(room => {
    room.cots.forEach(cot => {
      if (cot.occupied && cot.studentName) {
        resSheet.addRow({ name: cot.studentName, room: room.roomNumber, cot: cot.bedNumber, rent: cot.rentPerBed, pending: cot.pendingAmount });
      }
    });
  });
  applyHeaderStyle(resSheet, 1);
  autoFitColumns(resSheet);

  // Sheet 3: Mess
  const messSheet = workbook.addWorksheet('Mess Subscribers');
  messSheet.columns = [
    { header: 'Name', key: 'name' },
    { header: 'Phone', key: 'phone' },
    { header: 'Status', key: 'status' }
  ];
  messSubscribers.forEach(sub => messSheet.addRow({ name: sub.name, phone: sub.phone, status: sub.paymentStatus }));
  applyHeaderStyle(messSheet, 1);
  autoFitColumns(messSheet);

  await downloadWorkbook(workbook, `Combined_Report.xlsx`);
};

// 4. Contact List
export const exportContactList = async (dashboardData) => {
  const { matrixBeds } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Emergency Contacts');

  worksheet.columns = [
    { header: 'Name', key: 'name' },
    { header: 'Room', key: 'room' },
    { header: 'Cot', key: 'cot' },
    { header: 'Phone', key: 'phone' },
    { header: 'WhatsApp', key: 'whatsapp' },
    { header: 'Emergency Contact', key: 'emergency' },
    { header: 'Email', key: 'email' }
  ];

  const groupedRooms = groupMatrixBeds(matrixBeds);
  groupedRooms.forEach(room => {
    room.cots.forEach(cot => {
      if (cot.occupied && cot.studentName) {
        worksheet.addRow({
          name: cot.studentName,
          room: room.roomNumber,
          cot: cot.bedNumber,
          phone: cot.phone,
          whatsapp: cot.whatsappNumber,
          emergency: cot.emergencyContact,
          email: cot.email
        });
      }
    });
  });

  applyHeaderStyle(worksheet, 1);
  autoFitColumns(worksheet);
  await downloadWorkbook(workbook, `Emergency_Contact_List.xlsx`);
};

// 5. Defaulters List
export const exportDefaultersList = async (dashboardData) => {
  const { matrixBeds } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Defaulters');

  worksheet.columns = [
    { header: 'Name', key: 'name' },
    { header: 'Room', key: 'room' },
    { header: 'Cot', key: 'cot' },
    { header: 'Pending Amount', key: 'pending' },
    { header: 'Due Date', key: 'dueDate' },
    { header: 'Mobile Number', key: 'phone' },
    { header: 'WhatsApp Number', key: 'whatsapp' }
  ];

  const groupedRooms = groupMatrixBeds(matrixBeds);
  groupedRooms.forEach(room => {
    room.cots.forEach(cot => {
      if (cot.occupied && cot.pendingAmount > 0) {
        worksheet.addRow({
          name: cot.studentName,
          room: room.roomNumber,
          cot: cot.bedNumber,
          pending: cot.pendingAmount,
          dueDate: cot.nextDueDate,
          phone: cot.phone,
          whatsapp: cot.whatsappNumber
        });
      }
    });
  });

  applyHeaderStyle(worksheet, 1);
  autoFitColumns(worksheet);
  formatCurrency(worksheet, ['D']);
  await downloadWorkbook(workbook, `Defaulters_List.xlsx`);
};

// 6. Occupancy Report
export const exportOccupancyReport = async (dashboardData) => {
  const { matrixBeds, stats } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  
  const floorSheet = workbook.addWorksheet('Floor Occupancy');
  floorSheet.columns = [
    { header: 'Floor', key: 'floor' },
    { header: 'Total Beds', key: 'total' },
    { header: 'Occupied', key: 'occupied' },
    { header: 'Vacant', key: 'vacant' },
    { header: 'Occupancy %', key: 'percent' }
  ];
  
  const roomSheet = workbook.addWorksheet('Room Occupancy');
  roomSheet.columns = [
    { header: 'Floor', key: 'floor' },
    { header: 'Room', key: 'room' },
    { header: 'Total Beds', key: 'total' },
    { header: 'Occupied', key: 'occupied' },
    { header: 'Vacant', key: 'vacant' }
  ];

  const floorMap = {};
  const groupedRooms = groupMatrixBeds(matrixBeds);
  groupedRooms.forEach(room => {
    const f = room.floor || 1;
    if (!floorMap[f]) floorMap[f] = { total: 0, occupied: 0, vacant: 0 };
    const rTotal = room.capacity;
    const rOccupied = room.cots.filter(c => c.occupied).length;
    const rVacant = rTotal - rOccupied;
    
    floorMap[f].total += rTotal;
    floorMap[f].occupied += rOccupied;
    floorMap[f].vacant += rVacant;
    
    roomSheet.addRow({ floor: `Floor ${f}`, room: room.roomNumber, total: rTotal, occupied: rOccupied, vacant: rVacant });
  });

  Object.keys(floorMap).forEach(f => {
    const data = floorMap[f];
    const percent = data.total > 0 ? ((data.occupied / data.total) * 100).toFixed(1) + '%' : '0%';
    floorSheet.addRow({ floor: `Floor ${f}`, total: data.total, occupied: data.occupied, vacant: data.vacant, percent });
  });

  floorSheet.addRow({});
  floorSheet.addRow({ floor: 'TOTALS', total: stats?.totalStudents + stats?.vacantBeds, occupied: stats?.totalStudents, vacant: stats?.vacantBeds }).font = { bold: true };

  applyHeaderStyle(floorSheet, 1);
  applyHeaderStyle(roomSheet, 1);
  autoFitColumns(floorSheet);
  autoFitColumns(roomSheet);
  
  await downloadWorkbook(workbook, `Occupancy_Report.xlsx`);
};

// 7. Revenue Report
export const exportRevenueReport = async (dashboardData) => {
  const { stats } = dashboardData;
  const workbook = new window.ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Revenue Statistics');

  worksheet.columns = [
    { header: 'Metric', key: 'metric' },
    { header: 'Amount', key: 'amount' }
  ];

  worksheet.addRow({ metric: 'Expected Monthly Revenue', amount: stats?.expectedRev || 0 });
  worksheet.addRow({ metric: 'Collected Revenue', amount: stats?.totalCollected || 0 });
  worksheet.addRow({ metric: 'Pending Revenue', amount: stats?.pendingRev || 0 });
  
  applyHeaderStyle(worksheet, 1);
  autoFitColumns(worksheet);
  formatCurrency(worksheet, ['B']);
  
  await downloadWorkbook(workbook, `Revenue_Report.xlsx`);
};
